language: generic

sudo: false

before_install:
  - wget http://isabelle.in.tum.de/dist/Isabelle2016_app.tar.gz
  - tar -C .local/ -xzf Isabelle2016_app.tar.gz
  - .local/Isabelle2016/bin/isabelle build -b -s -v HOL

install: true

before_script: export PATH=`pwd`/.local/Isabelle2016/bin:$PATH

script: isabelle build -d . isabelle-ci-test
